<!DOCTYPE HTML>
<html>
    <head>
        <title>Galería de fotos</title>
        <meta charset="utf-8">
        <meta content="width=device-width, initial-scale=1" name="viewport">
    </head>
    <body>
        <div class="container">
            <h2>Galería de fotos</h2>
            <p>Hola! Te damos la bienvenida a tu Galería de fotos, aquí puedes ver todos los álbumes y las fotos dentro de cada uno.</p>
            <br /><br />
            <a href="/albums">Ver álbumes</a>
        </div>
    </body>
</html>